"""
Financial models: Chart of Accounts, Posting Groups, Invoices, GL entries.

Design notes:
- GLAccount holds the chart of accounts (standard double-entry structure)
- PostingGroup maps transaction types to their GL accounts (replaces hardcoded logic)
- Invoice is the customer-facing document (new vehicle, accessory, workshop, parts)
- InvoiceLine is a line on that invoice
- GLEntry is the immutable double-entry ledger record

All financial documents live in MongoDB but are structured for easy migration
to a relational DB if needed. Each document carries dealer_group_id + outlet_id.
"""
from datetime import datetime
from decimal import Decimal
from typing import Optional
from beanie import Document
from pydantic import BaseModel, Field
from pymongo import IndexModel, ASCENDING


# ---------------------------------------------------------------------------
# Chart of accounts
# ---------------------------------------------------------------------------

class GLAccount(Document):
    dealer_group_id: str

    code: str            # e.g. "4000"
    name: str            # e.g. "Vehicle Sales Revenue"
    # "asset" | "liability" | "equity" | "revenue" | "expense"
    account_type: str
    # "sales" | "cogs" | "debtor" | "creditor" | "tax" | "bank" | "overhead"
    category: str

    is_active: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "gl_accounts"
        indexes = [
            IndexModel([("dealer_group_id", ASCENDING), ("code", ASCENDING)], unique=True),
        ]


# ---------------------------------------------------------------------------
# Posting groups — define which GL accounts to use per transaction type
# ---------------------------------------------------------------------------

class PostingGroup(Document):
    dealer_group_id: str

    name: str           # e.g. "New Vehicle Sale", "Workshop Labour", "Parts Sale"
    # "new_vehicle" | "used_vehicle" | "accessory" | "workshop_labour" | "parts" | "sublet"
    transaction_type: str

    revenue_gl_code: str   # GL code for the revenue line
    cogs_gl_code: Optional[str] = None   # GL code for cost of goods (vehicle sales)
    debtor_gl_code: str = "2000"         # Trade debtors
    tax_gl_code: str = "2100"            # VAT control
    tax_rate: float = 20.0               # Standard UK VAT %

    is_active: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "posting_groups"
        indexes = [
            IndexModel([("dealer_group_id", ASCENDING), ("transaction_type", ASCENDING)], unique=True),
        ]


# ---------------------------------------------------------------------------
# Invoice
# ---------------------------------------------------------------------------

class InvoiceLine(BaseModel):
    line_number: int
    description: str
    quantity: float = 1.0
    unit_price: float
    discount_pct: float = 0.0
    net_amount: float
    tax_rate: float = 20.0
    tax_amount: float
    gross_amount: float
    posting_group_type: str  # maps to PostingGroup.transaction_type
    gl_revenue_code: str
    reference: Optional[str] = None  # e.g. op_code, part_number


class Invoice(Document):
    dealer_group_id: str
    outlet_id: str

    # Human-readable invoice number, generated by the system
    invoice_number: str

    # "new_vehicle" | "used_vehicle" | "workshop" | "parts" | "accessory"
    invoice_type: str

    customer_id: Optional[str] = None
    customer_name: str
    customer_address: Optional[str] = None
    customer_email: Optional[str] = None

    # Linked source document
    order_id: Optional[str] = None
    wip_id: Optional[str] = None

    vehicle_registration: Optional[str] = None
    vehicle_description: Optional[str] = None

    lines: list[InvoiceLine] = Field(default_factory=list)

    net_total: float = 0.0
    tax_total: float = 0.0
    gross_total: float = 0.0

    # "draft" | "posted" | "paid" | "credited" | "void"
    status: str = "draft"

    invoice_date: datetime = Field(default_factory=datetime.utcnow)
    due_date: Optional[datetime] = None
    paid_at: Optional[datetime] = None

    # Template used for printing / PDF generation
    template_id: str = "default"

    # Email delivery
    emailed_to: Optional[str] = None
    emailed_at: Optional[datetime] = None

    # GL posting flag — True once GLEntry records have been created
    gl_posted: bool = False
    gl_posted_at: Optional[datetime] = None

    created_by: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "invoices"
        indexes = [
            IndexModel([("dealer_group_id", ASCENDING), ("invoice_number", ASCENDING)], unique=True),
            IndexModel([("dealer_group_id", ASCENDING), ("outlet_id", ASCENDING)]),
            IndexModel([("dealer_group_id", ASCENDING), ("status", ASCENDING)]),
            IndexModel([("customer_id", ASCENDING)], sparse=True),
            IndexModel([("wip_id", ASCENDING)], sparse=True),
            IndexModel([("order_id", ASCENDING)], sparse=True),
            IndexModel([("invoice_date", ASCENDING)]),
        ]


# ---------------------------------------------------------------------------
# General Ledger entries (double-entry)
# ---------------------------------------------------------------------------

class GLEntry(Document):
    """
    Immutable double-entry ledger record.
    Every invoice posting creates a set of balanced debit/credit pairs.
    """
    dealer_group_id: str
    outlet_id: str

    invoice_id: str
    invoice_number: str

    entry_date: datetime = Field(default_factory=datetime.utcnow)

    gl_code: str
    gl_name: str
    # "debit" | "credit"
    entry_type: str

    amount: float  # Always positive; entry_type determines direction

    description: str
    reference: Optional[str] = None  # Invoice number or line reference

    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "gl_entries"
        indexes = [
            IndexModel([("dealer_group_id", ASCENDING), ("invoice_id", ASCENDING)]),
            IndexModel([("dealer_group_id", ASCENDING), ("gl_code", ASCENDING)]),
            IndexModel([("dealer_group_id", ASCENDING), ("entry_date", ASCENDING)]),
        ]


# ---------------------------------------------------------------------------
# Invoice template (configurable per dealer group / outlet)
# ---------------------------------------------------------------------------

class InvoiceTemplate(Document):
    dealer_group_id: str
    outlet_id: Optional[str] = None  # None = group-wide default

    template_id: str  # e.g. "default", "workshop", "vehicle_sale"
    name: str

    # Jinja2 / HTML template string stored here
    html_template: str

    dealer_name: str
    dealer_address: str
    dealer_phone: Optional[str] = None
    dealer_email: Optional[str] = None
    dealer_vat_number: Optional[str] = None
    dealer_logo_url: Optional[str] = None

    is_active: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "invoice_templates"
        indexes = [
            IndexModel([("dealer_group_id", ASCENDING), ("template_id", ASCENDING)], unique=True),
        ]


# ---------------------------------------------------------------------------
# Credit Notes — reversals of posted invoices
# ---------------------------------------------------------------------------

class CreditNote(Document):
    dealer_group_id: str
    outlet_id: str

    credit_note_number: str

    original_invoice_id: str
    original_invoice_number: str

    # "pricing_error" | "warranty_adjustment" | "goodwill" | "return" | "other"
    reason: str
    reason_notes: Optional[str] = None

    lines: list[InvoiceLine] = Field(default_factory=list)

    net_total: float = 0.0
    tax_total: float = 0.0
    gross_total: float = 0.0

    customer_id: Optional[str] = None
    customer_name: str

    # "draft" | "posted" | "applied"
    status: str = "draft"

    gl_posted: bool = False
    gl_posted_at: Optional[datetime] = None

    created_by: str  # User ID

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "credit_notes"
        indexes = [
            IndexModel(
                [("dealer_group_id", ASCENDING), ("credit_note_number", ASCENDING)],
                unique=True,
            ),
            IndexModel([("dealer_group_id", ASCENDING), ("original_invoice_id", ASCENDING)]),
            IndexModel([("customer_id", ASCENDING)], sparse=True),
        ]
